ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "/home/asoares/Documentos/GitPessoal/instagram/src/instabot.py", line 869, in auto_unfollow
    all_data = json.loads(re.search('{"activity.+probably_has_app', r.text, re.DOTALL).group(0)+'":""}')['entry_data']['ProfilePage'][0]
AttributeError: 'NoneType' object has no attribute 'group'
ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "/home/asoares/Documentos/GitPessoal/instagram/src/instabot.py", line 869, in auto_unfollow
    all_data = json.loads(re.search('{"activity.+probably_has_app', r.text, re.DOTALL).group(0)+'":""}')['entry_data']['ProfilePage'][0]
AttributeError: 'NoneType' object has no attribute 'group'
ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "/home/asoares/Documentos/GitPessoal/instagram/src/instabot.py", line 869, in auto_unfollow
    all_data = json.loads(re.search('{"activity.+probably_has_app', r.text, re.DOTALL).group(0)+'":""}')['entry_data']['ProfilePage'][0]
AttributeError: 'NoneType' object has no attribute 'group'
ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "/home/asoares/Documentos/GitPessoal/instagram/src/instabot.py", line 869, in auto_unfollow
    all_data = json.loads(re.search('{"activity.+probably_has_app', r.text, re.DOTALL).group(0)+'":""}')['entry_data']['ProfilePage'][0]
AttributeError: 'NoneType' object has no attribute 'group'
ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "/home/asoares/Documentos/GitPessoal/instagram/src/instabot.py", line 869, in auto_unfollow
    all_data = json.loads(re.search('{"activity.+probably_has_app', r.text, re.DOTALL).group(0)+'":""}')['entry_data']['ProfilePage'][0]
AttributeError: 'NoneType' object has no attribute 'group'
ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "/home/asoares/Documentos/GitPessoal/instagram/src/instabot.py", line 869, in auto_unfollow
    all_data = json.loads(re.search('{"activity.+probably_has_app', r.text, re.DOTALL).group(0)+'":""}')['entry_data']['ProfilePage'][0]
AttributeError: 'NoneType' object has no attribute 'group'
ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "/home/asoares/Documentos/GitPessoal/instagram/src/instabot.py", line 869, in auto_unfollow
    all_data = json.loads(re.search('{"activity.+probably_has_app', r.text, re.DOTALL).group(0)+'":""}')['entry_data']['ProfilePage'][0]
AttributeError: 'NoneType' object has no attribute 'group'
ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "/home/asoares/Documentos/GitPessoal/instagram/src/instabot.py", line 869, in auto_unfollow
    all_data = json.loads(re.search('{"activity.+probably_has_app', r.text, re.DOTALL).group(0)+'":""}')['entry_data']['ProfilePage'][0]
AttributeError: 'NoneType' object has no attribute 'group'
ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "/home/asoares/Documentos/GitPessoal/instagram/src/instabot.py", line 869, in auto_unfollow
    all_data = json.loads('{"entry_data":'+re.search('{"ProfilePage.+probably_has_app', info.text, re.DOTALL).group(0)+'":""}')['entry_data']['ProfilePage'][0]
NameError: name 'info' is not defined
